## 应用名称
#spring.application.name=payment-demo

server:
  port: 8090


spring:
  application:
    name: payment-demo
  # 调整返回的时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 # 东八区

